data class DatasetItem(
    val age: String,
    val gender: String,
    val smoking: String,
    val fingerDiscolor: String,
    val mentalStress: String,
    val pollution: String,
    val illness: String,
    val energy: String,
    val immune: String,
    val breathing: String,
    val throat: String,
    val oxygen: String,
    val chest: String,
    val familyHistory: String,
    val familySmoke: String,
    val stressImmune: String,
    val result: String
)
